"""initial schema

Revision ID: cb2d12318358
Revises: 
Create Date: 2026-09-06 17:10:31.600133+00:00
"""
from collections.abc import Sequence

import sqlalchemy as sa
from alembic import op
from sqlalchemy.dialects import postgresql
revision: str = 'cb2d12318358'
down_revision: str | None = None
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('ad_metrics_raw',
    sa.Column('id', sa.BigInteger(), autoincrement=True, nullable=False),
    sa.Column('source', sa.Text(), nullable=False),
    sa.Column('metric_date', sa.Date(), nullable=False),
    sa.Column('external_ad_id', sa.Text(), nullable=True),
    sa.Column('payload', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('ingested_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_ad_metrics_raw')),
    sa.UniqueConstraint('source', 'metric_date', 'external_ad_id', 'ingested_at', name=op.f('uq_ad_metrics_raw_source_metric_date_external_ad_id_ingested_at'))
    )
    op.create_table('ai_recommendations',
    sa.Column('id', sa.BigInteger(), autoincrement=True, nullable=False),
    sa.Column('run_id', sa.BigInteger(), nullable=True),
    sa.Column('decision_type', sa.Enum('PROMOTE', 'KEEP', 'REPLACE', 'PAUSE', 'RESUME', 'INCREASE_BUDGET', 'DECREASE_BUDGET', 'REJECT', 'RESIZE_PORTFOLIO', 'ADJUST_PARAMETER', 'NO_ACTION', name='decision_type'), nullable=False),
    sa.Column('subject_type', sa.Text(), nullable=False),
    sa.Column('subject_id', sa.Text(), nullable=True),
    sa.Column('rationale', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('confidence', sa.Numeric(precision=4, scale=3), nullable=True),
    sa.Column('expected_impact', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('status', sa.Text(), server_default='PENDING', nullable=False),
    sa.Column('reviewed_by', sa.Text(), nullable=True),
    sa.Column('reviewed_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('executed_decision_id', sa.BigInteger(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_ai_recommendations'))
    )
    op.create_table('alerts',
    sa.Column('id', sa.BigInteger(), autoincrement=True, nullable=False),
    sa.Column('severity', sa.Text(), nullable=False),
    sa.Column('code', sa.Text(), nullable=False),
    sa.Column('subject_type', sa.Text(), nullable=True),
    sa.Column('subject_id', sa.Text(), nullable=True),
    sa.Column('message', sa.Text(), nullable=False),
    sa.Column('details', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('acknowledged_by', sa.Text(), nullable=True),
    sa.Column('acknowledged_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_alerts'))
    )
    op.create_table('audit_logs',
    sa.Column('id', sa.BigInteger(), autoincrement=True, nullable=False),
    sa.Column('actor', sa.Text(), nullable=False),
    sa.Column('action', sa.Text(), nullable=False),
    sa.Column('entity_type', sa.Text(), nullable=False),
    sa.Column('entity_id', sa.Text(), nullable=True),
    sa.Column('before', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('after', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('request_id', sa.Text(), nullable=True),
    sa.Column('ip_address', postgresql.INET(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_audit_logs'))
    )
    op.create_table('campaigns',
    sa.Column('id', sa.BigInteger(), autoincrement=True, nullable=False),
    sa.Column('external_id', sa.Text(), nullable=True),
    sa.Column('platform', sa.Text(), server_default='meta', nullable=False),
    sa.Column('ad_account_id', sa.Text(), nullable=False),
    sa.Column('name', sa.Text(), nullable=False),
    sa.Column('objective', sa.Text(), nullable=False),
    sa.Column('status', sa.Text(), nullable=False),
    sa.Column('created_paused', sa.Boolean(), server_default='true', nullable=False),
    sa.Column('review_status', sa.Enum('UNREVIEWED', 'APPROVED', 'REJECTED', 'ARCHIVED', name='campaign_review_status'), server_default='UNREVIEWED', nullable=False),
    sa.Column('reviewed_by', sa.Text(), nullable=True),
    sa.Column('reviewed_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('daily_budget', sa.Numeric(precision=12, scale=2), nullable=True),
    sa.Column('created_by_run_id', sa.BigInteger(), nullable=True),
    sa.Column('dry_run', sa.Boolean(), server_default='false', nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.CheckConstraint('created_paused = TRUE', name=op.f('ck_campaigns_campaigns_must_be_created_paused')),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_campaigns')),
    sa.UniqueConstraint('external_id', name=op.f('uq_campaigns_external_id'))
    )
    op.create_table('config_parameters',
    sa.Column('key', sa.Text(), nullable=False),
    sa.Column('value', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('value_type', sa.Text(), nullable=False),
    sa.Column('min_value', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('max_value', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('description', sa.Text(), nullable=False),
    sa.Column('ai_adjustable', sa.Boolean(), server_default='false', nullable=False),
    sa.Column('updated_by', sa.Text(), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('key', name=op.f('pk_config_parameters'))
    )
    op.create_table('execution_locks',
    sa.Column('lock_name', sa.Text(), nullable=False),
    sa.Column('acquired_by', sa.Text(), nullable=False),
    sa.Column('acquired_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('expires_at', sa.DateTime(timezone=True), nullable=False),
    sa.PrimaryKeyConstraint('lock_name', name=op.f('pk_execution_locks'))
    )
    op.create_table('idempotency_keys',
    sa.Column('key', sa.Text(), nullable=False),
    sa.Column('endpoint', sa.Text(), nullable=False),
    sa.Column('request_hash', sa.Text(), nullable=False),
    sa.Column('response_body', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('status_code', sa.Integer(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('expires_at', sa.DateTime(timezone=True), nullable=False),
    sa.PrimaryKeyConstraint('key', name=op.f('pk_idempotency_keys'))
    )
    op.create_table('llm_calls',
    sa.Column('id', sa.BigInteger(), autoincrement=True, nullable=False),
    sa.Column('purpose', sa.Text(), nullable=False),
    sa.Column('provider', sa.Text(), nullable=False),
    sa.Column('model', sa.Text(), nullable=False),
    sa.Column('prompt', sa.Text(), nullable=False),
    sa.Column('response', sa.Text(), nullable=True),
    sa.Column('input_tokens', sa.Integer(), nullable=True),
    sa.Column('output_tokens', sa.Integer(), nullable=True),
    sa.Column('cost_usd', sa.Numeric(precision=10, scale=6), nullable=True),
    sa.Column('latency_ms', sa.Integer(), nullable=True),
    sa.Column('success', sa.Boolean(), nullable=False),
    sa.Column('error', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_llm_calls'))
    )
    op.create_table('marketplaces',
    sa.Column('id', sa.SmallInteger(), autoincrement=True, nullable=False),
    sa.Column('code', sa.Text(), nullable=False),
    sa.Column('display_name', sa.Text(), nullable=False),
    sa.Column('currency', sa.CHAR(length=3), server_default='BRL', nullable=False),
    sa.Column('is_active', sa.Boolean(), server_default='true', nullable=False),
    sa.Column('adapter_class', sa.Text(), nullable=False),
    sa.Column('config', postgresql.JSONB(astext_type=sa.Text()), server_default='{}', nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_marketplaces')),
    sa.UniqueConstraint('code', name=op.f('uq_marketplaces_code'))
    )
    op.create_table('portfolio_snapshots',
    sa.Column('snapshot_date', sa.Date(), nullable=False),
    sa.Column('active_count', sa.Integer(), nullable=False),
    sa.Column('exploration_count', sa.Integer(), nullable=False),
    sa.Column('exploitation_count', sa.Integer(), nullable=False),
    sa.Column('winner_count', sa.Integer(), nullable=False),
    sa.Column('total_daily_budget', sa.Numeric(precision=12, scale=2), nullable=False),
    sa.Column('recommended_size', sa.Integer(), nullable=True),
    sa.Column('sizing_rationale', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('snapshot_date', name=op.f('pk_portfolio_snapshots'))
    )
    op.create_table('simulations',
    sa.Column('id', sa.BigInteger(), autoincrement=True, nullable=False),
    sa.Column('inputs', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('outputs', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('assumptions', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('created_by', sa.Text(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_simulations'))
    )
    op.create_table('workflow_runs',
    sa.Column('id', sa.BigInteger(), autoincrement=True, nullable=False),
    sa.Column('workflow_name', sa.Text(), nullable=False),
    sa.Column('n8n_execution_id', sa.Text(), nullable=True),
    sa.Column('status', sa.Enum('RUNNING', 'SUCCESS', 'FAILED', 'ABORTED', 'SKIPPED', name='run_status'), server_default='RUNNING', nullable=False),
    sa.Column('dry_run', sa.Boolean(), server_default='false', nullable=False),
    sa.Column('started_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('finished_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('items_processed', sa.Integer(), nullable=True),
    sa.Column('error', sa.Text(), nullable=True),
    sa.Column('summary', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_workflow_runs'))
    )
    op.create_table('ad_sets',
    sa.Column('id', sa.BigInteger(), autoincrement=True, nullable=False),
    sa.Column('campaign_id', sa.BigInteger(), nullable=False),
    sa.Column('external_id', sa.Text(), nullable=True),
    sa.Column('name', sa.Text(), nullable=False),
    sa.Column('status', sa.Text(), nullable=False),
    sa.Column('daily_budget', sa.Numeric(precision=12, scale=2), nullable=True),
    sa.Column('targeting', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['campaign_id'], ['campaigns.id'], name=op.f('fk_ad_sets_campaign_id_campaigns')),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_ad_sets')),
    sa.UniqueConstraint('external_id', name=op.f('uq_ad_sets_external_id'))
    )
    op.create_table('conversions_raw',
    sa.Column('id', sa.BigInteger(), autoincrement=True, nullable=False),
    sa.Column('marketplace_id', sa.SmallInteger(), nullable=False),
    sa.Column('source', sa.Text(), nullable=False),
    sa.Column('external_order_id', sa.Text(), nullable=True),
    sa.Column('sub_id', sa.Text(), nullable=True),
    sa.Column('conversion_date', sa.Date(), nullable=True),
    sa.Column('commission_value', sa.Numeric(precision=14, scale=2), nullable=True),
    sa.Column('order_value', sa.Numeric(precision=14, scale=2), nullable=True),
    sa.Column('status', sa.Text(), nullable=True),
    sa.Column('fraud_status', sa.Text(), nullable=True),
    sa.Column('settlement', sa.Enum('PROVISIONAL', 'PARTIAL', 'SETTLED', name='settlement_status'), server_default='PROVISIONAL', nullable=False),
    sa.Column('payload', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('ingested_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['marketplace_id'], ['marketplaces.id'], name=op.f('fk_conversions_raw_marketplace_id_marketplaces')),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_conversions_raw')),
    sa.UniqueConstraint('marketplace_id', 'source', 'external_order_id', 'sub_id', name=op.f('uq_conversions_raw_marketplace_id_source_external_order_id_sub_id'))
    )
    op.create_index('ix_conversions_raw_sub_id_conversion_date', 'conversions_raw', ['sub_id', 'conversion_date'], unique=False)
    op.create_table('products',
    sa.Column('id', sa.BigInteger(), autoincrement=True, nullable=False),
    sa.Column('marketplace_id', sa.SmallInteger(), nullable=False),
    sa.Column('external_product_id', sa.Text(), nullable=False),
    sa.Column('external_shop_id', sa.Text(), nullable=True),
    sa.Column('title', sa.Text(), nullable=False),
    sa.Column('category_path', postgresql.ARRAY(sa.String()), nullable=True),
    sa.Column('product_url', sa.Text(), nullable=False),
    sa.Column('image_url', sa.Text(), nullable=True),
    sa.Column('first_seen_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('last_seen_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('raw_payload', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.ForeignKeyConstraint(['marketplace_id'], ['marketplaces.id'], name=op.f('fk_products_marketplace_id_marketplaces')),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_products')),
    sa.UniqueConstraint('marketplace_id', 'external_product_id', name=op.f('uq_products_marketplace_id_external_product_id'))
    )
    op.create_table('affiliate_links',
    sa.Column('id', sa.BigInteger(), autoincrement=True, nullable=False),
    sa.Column('product_id', sa.BigInteger(), nullable=False),
    sa.Column('campaign_id', sa.BigInteger(), nullable=True),
    sa.Column('creative_id', sa.BigInteger(), nullable=True),
    sa.Column('channel', sa.Text(), nullable=False),
    sa.Column('sub_id', sa.Text(), nullable=False),
    sa.Column('utm_source', sa.Text(), nullable=True),
    sa.Column('utm_medium', sa.Text(), nullable=True),
    sa.Column('utm_campaign', sa.Text(), nullable=True),
    sa.Column('utm_content', sa.Text(), nullable=True),
    sa.Column('utm_term', sa.Text(), nullable=True),
    sa.Column('short_url', sa.Text(), nullable=True),
    sa.Column('raw_url', sa.Text(), nullable=False),
    sa.Column('generated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('revoked_at', sa.DateTime(timezone=True), nullable=True),
    sa.ForeignKeyConstraint(['product_id'], ['products.id'], name=op.f('fk_affiliate_links_product_id_products')),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_affiliate_links')),
    sa.UniqueConstraint('sub_id', name=op.f('uq_affiliate_links_sub_id'))
    )
    op.create_index('ix_affiliate_links_product_id_active', 'affiliate_links', ['product_id'], unique=False, postgresql_where=sa.text('revoked_at IS NULL'))
    op.create_table('ai_decisions',
    sa.Column('id', sa.BigInteger(), autoincrement=True, nullable=False),
    sa.Column('run_id', sa.BigInteger(), nullable=True),
    sa.Column('recommendation_id', sa.BigInteger(), nullable=True),
    sa.Column('mode', sa.Enum('RECOMMEND', 'EXECUTE', name='decision_mode'), nullable=False),
    sa.Column('decision_type', sa.Enum('PROMOTE', 'KEEP', 'REPLACE', 'PAUSE', 'RESUME', 'INCREASE_BUDGET', 'DECREASE_BUDGET', 'REJECT', 'RESIZE_PORTFOLIO', 'ADJUST_PARAMETER', 'NO_ACTION', name='decision_type'), nullable=False),
    sa.Column('autonomy_level', sa.SmallInteger(), nullable=False),
    sa.Column('dry_run', sa.Boolean(), server_default='false', nullable=False),
    sa.Column('subject_type', sa.Text(), nullable=False),
    sa.Column('product_in', sa.BigInteger(), nullable=True),
    sa.Column('product_out', sa.BigInteger(), nullable=True),
    sa.Column('payload', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('engine_version', sa.Text(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['product_in'], ['products.id'], name=op.f('fk_ai_decisions_product_in_products')),
    sa.ForeignKeyConstraint(['product_out'], ['products.id'], name=op.f('fk_ai_decisions_product_out_products')),
    sa.ForeignKeyConstraint(['recommendation_id'], ['ai_recommendations.id'], name=op.f('fk_ai_decisions_recommendation_id_ai_recommendations')),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_ai_decisions'))
    )
    op.create_index('ix_ai_decisions_created_at', 'ai_decisions', ['created_at'], unique=False)
    op.create_table('creatives',
    sa.Column('id', sa.BigInteger(), autoincrement=True, nullable=False),
    sa.Column('product_id', sa.BigInteger(), nullable=False),
    sa.Column('format', sa.Text(), nullable=False),
    sa.Column('headline', sa.Text(), nullable=True),
    sa.Column('primary_text', sa.Text(), nullable=True),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('call_to_action', sa.Text(), nullable=True),
    sa.Column('asset_urls', postgresql.ARRAY(sa.String()), nullable=True),
    sa.Column('generated_by', sa.Text(), nullable=False),
    sa.Column('llm_call_id', sa.BigInteger(), nullable=True),
    sa.Column('approved_by', sa.Text(), nullable=True),
    sa.Column('approved_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['product_id'], ['products.id'], name=op.f('fk_creatives_product_id_products')),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_creatives'))
    )
    op.create_table('opportunity_scores',
    sa.Column('id', sa.BigInteger(), autoincrement=True, nullable=False),
    sa.Column('product_id', sa.BigInteger(), nullable=False),
    sa.Column('score', sa.Numeric(precision=6, scale=3), nullable=False),
    sa.Column('algorithm_version', sa.Text(), nullable=False),
    sa.Column('components', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('data_available', sa.Boolean(), nullable=False),
    sa.Column('missing_fields', postgresql.ARRAY(sa.String()), server_default='{}', nullable=False),
    sa.Column('llm_used', sa.Boolean(), server_default='false', nullable=False),
    sa.Column('llm_call_id', sa.BigInteger(), nullable=True),
    sa.Column('computed_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['product_id'], ['products.id'], name=op.f('fk_opportunity_scores_product_id_products')),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_opportunity_scores'))
    )
    op.create_index('ix_opportunity_scores_product_id_computed_at', 'opportunity_scores', ['product_id', 'computed_at'], unique=False)
    op.create_table('performance_daily',
    sa.Column('id', sa.BigInteger(), autoincrement=True, nullable=False),
    sa.Column('metric_date', sa.Date(), nullable=False),
    sa.Column('product_id', sa.BigInteger(), nullable=False),
    sa.Column('campaign_id', sa.BigInteger(), nullable=True),
    sa.Column('channel', sa.Text(), nullable=False),
    sa.Column('impressions', sa.BigInteger(), nullable=True),
    sa.Column('clicks', sa.BigInteger(), nullable=True),
    sa.Column('ad_spend', sa.Numeric(precision=14, scale=2), nullable=True),
    sa.Column('conversions', sa.Integer(), nullable=True),
    sa.Column('revenue', sa.Numeric(precision=14, scale=2), nullable=True),
    sa.Column('profit', sa.Numeric(precision=14, scale=2), nullable=True),
    sa.Column('ctr', sa.Numeric(precision=8, scale=5), nullable=True),
    sa.Column('cpc', sa.Numeric(precision=12, scale=4), nullable=True),
    sa.Column('cvr', sa.Numeric(precision=8, scale=5), nullable=True),
    sa.Column('roi', sa.Numeric(precision=10, scale=4), nullable=True),
    sa.Column('roas', sa.Numeric(precision=10, scale=4), nullable=True),
    sa.Column('epc', sa.Numeric(precision=12, scale=4), nullable=True),
    sa.Column('cost_data_available', sa.Boolean(), server_default='false', nullable=False),
    sa.Column('revenue_data_available', sa.Boolean(), server_default='false', nullable=False),
    sa.Column('settlement', sa.Enum('PROVISIONAL', 'PARTIAL', 'SETTLED', name='settlement_status'), server_default='PROVISIONAL', nullable=False),
    sa.Column('computed_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['campaign_id'], ['campaigns.id'], name=op.f('fk_performance_daily_campaign_id_campaigns')),
    sa.ForeignKeyConstraint(['product_id'], ['products.id'], name=op.f('fk_performance_daily_product_id_products')),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_performance_daily')),
    sa.UniqueConstraint('metric_date', 'product_id', 'campaign_id', 'channel', name=op.f('uq_performance_daily_metric_date_product_id_campaign_id_channel'))
    )
    op.create_index('ix_performance_daily_product_id_metric_date', 'performance_daily', ['product_id', 'metric_date'], unique=False)
    op.create_table('performance_scores',
    sa.Column('id', sa.BigInteger(), autoincrement=True, nullable=False),
    sa.Column('product_id', sa.BigInteger(), nullable=False),
    sa.Column('window_days', sa.SmallInteger(), nullable=False),
    sa.Column('score', sa.Numeric(precision=6, scale=3), nullable=True),
    sa.Column('algorithm_version', sa.Text(), nullable=False),
    sa.Column('components', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('data_available', sa.Boolean(), nullable=False),
    sa.Column('sample_sufficient', sa.Boolean(), nullable=False),
    sa.Column('settlement', sa.Enum('PROVISIONAL', 'PARTIAL', 'SETTLED', name='settlement_status'), nullable=False),
    sa.Column('computed_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['product_id'], ['products.id'], name=op.f('fk_performance_scores_product_id_products')),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_performance_scores')),
    sa.UniqueConstraint('product_id', 'window_days', 'computed_at', name=op.f('uq_performance_scores_product_id_window_days_computed_at'))
    )
    op.create_table('portfolio_products',
    sa.Column('id', sa.BigInteger(), autoincrement=True, nullable=False),
    sa.Column('product_id', sa.BigInteger(), nullable=False),
    sa.Column('tier', sa.Enum('EXPLORATION', 'EXPLOITATION', name='portfolio_tier'), nullable=False),
    sa.Column('entered_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('exited_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('exit_reason_code', sa.Text(), nullable=True),
    sa.Column('allocated_daily_budget', sa.Numeric(precision=12, scale=2), server_default='0', nullable=False),
    sa.Column('priority_weight', sa.Numeric(precision=6, scale=3), server_default='1.0', nullable=False),
    sa.Column('entry_decision_id', sa.BigInteger(), nullable=True),
    sa.Column('exit_decision_id', sa.BigInteger(), nullable=True),
    sa.ForeignKeyConstraint(['product_id'], ['products.id'], name=op.f('fk_portfolio_products_product_id_products')),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_portfolio_products'))
    )
    op.create_index('uq_portfolio_products_active_product', 'portfolio_products', ['product_id'], unique=True, postgresql_where=sa.text('exited_at IS NULL'))
    op.create_table('product_snapshots',
    sa.Column('id', sa.BigInteger(), autoincrement=True, nullable=False),
    sa.Column('product_id', sa.BigInteger(), nullable=False),
    sa.Column('captured_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('price', sa.Numeric(precision=14, scale=2), nullable=True),
    sa.Column('original_price', sa.Numeric(precision=14, scale=2), nullable=True),
    sa.Column('commission_rate', sa.Numeric(precision=7, scale=4), nullable=True),
    sa.Column('commission_value', sa.Numeric(precision=14, scale=2), nullable=True),
    sa.Column('rating', sa.Numeric(precision=3, scale=2), nullable=True),
    sa.Column('rating_count', sa.Integer(), nullable=True),
    sa.Column('sales_volume', sa.Integer(), nullable=True),
    sa.Column('stock', sa.Integer(), nullable=True),
    sa.Column('data_available', postgresql.JSONB(astext_type=sa.Text()), server_default='{}', nullable=False),
    sa.Column('raw_payload', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.ForeignKeyConstraint(['product_id'], ['products.id'], name=op.f('fk_product_snapshots_product_id_products')),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_product_snapshots'))
    )
    op.create_index('ix_product_snapshots_product_id_captured_at', 'product_snapshots', ['product_id', 'captured_at'], unique=False)
    op.create_table('product_state_transitions',
    sa.Column('id', sa.BigInteger(), autoincrement=True, nullable=False),
    sa.Column('product_id', sa.BigInteger(), nullable=False),
    sa.Column('from_state', sa.Enum('DISCOVERY', 'QUALIFICATION', 'CANDIDATE', 'TEST', 'ACTIVE', 'WINNER', 'REJECTED', 'PAUSED', 'UNDER_REVIEW', 'REPLACED', 'EXPIRED', name='product_state'), nullable=True),
    sa.Column('to_state', sa.Enum('DISCOVERY', 'QUALIFICATION', 'CANDIDATE', 'TEST', 'ACTIVE', 'WINNER', 'REJECTED', 'PAUSED', 'UNDER_REVIEW', 'REPLACED', 'EXPIRED', name='product_state'), nullable=False),
    sa.Column('reason_code', sa.Text(), nullable=False),
    sa.Column('reason_detail', sa.Text(), nullable=True),
    sa.Column('decision_id', sa.BigInteger(), nullable=True),
    sa.Column('actor', sa.Text(), nullable=False),
    sa.Column('metrics_used', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['product_id'], ['products.id'], name=op.f('fk_product_state_transitions_product_id_products')),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_product_state_transitions'))
    )
    op.create_index('ix_product_state_transitions_product_id_created_at', 'product_state_transitions', ['product_id', 'created_at'], unique=False)
    op.create_table('ads',
    sa.Column('id', sa.BigInteger(), autoincrement=True, nullable=False),
    sa.Column('ad_set_id', sa.BigInteger(), nullable=False),
    sa.Column('product_id', sa.BigInteger(), nullable=False),
    sa.Column('creative_id', sa.BigInteger(), nullable=True),
    sa.Column('affiliate_link_id', sa.BigInteger(), nullable=True),
    sa.Column('external_id', sa.Text(), nullable=True),
    sa.Column('status', sa.Text(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['ad_set_id'], ['ad_sets.id'], name=op.f('fk_ads_ad_set_id_ad_sets')),
    sa.ForeignKeyConstraint(['affiliate_link_id'], ['affiliate_links.id'], name=op.f('fk_ads_affiliate_link_id_affiliate_links')),
    sa.ForeignKeyConstraint(['creative_id'], ['creatives.id'], name=op.f('fk_ads_creative_id_creatives')),
    sa.ForeignKeyConstraint(['product_id'], ['products.id'], name=op.f('fk_ads_product_id_products')),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_ads')),
    sa.UniqueConstraint('external_id', name=op.f('uq_ads_external_id'))
    )
    op.create_table('budget_ledger',
    sa.Column('id', sa.BigInteger(), autoincrement=True, nullable=False),
    sa.Column('ledger_date', sa.Date(), nullable=False),
    sa.Column('entry_type', sa.Text(), nullable=False),
    sa.Column('scope', sa.Text(), nullable=False),
    sa.Column('product_id', sa.BigInteger(), nullable=True),
    sa.Column('campaign_id', sa.BigInteger(), nullable=True),
    sa.Column('amount', sa.Numeric(precision=14, scale=2), nullable=False),
    sa.Column('decision_id', sa.BigInteger(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['campaign_id'], ['campaigns.id'], name=op.f('fk_budget_ledger_campaign_id_campaigns')),
    sa.ForeignKeyConstraint(['decision_id'], ['ai_decisions.id'], name=op.f('fk_budget_ledger_decision_id_ai_decisions')),
    sa.ForeignKeyConstraint(['product_id'], ['products.id'], name=op.f('fk_budget_ledger_product_id_products')),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_budget_ledger'))
    )
    op.create_index('ix_budget_ledger_ledger_date_scope', 'budget_ledger', ['ledger_date', 'scope'], unique=False)
    op.create_table('config_parameter_history',
    sa.Column('id', sa.BigInteger(), autoincrement=True, nullable=False),
    sa.Column('key', sa.Text(), nullable=False),
    sa.Column('old_value', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('new_value', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('changed_by', sa.Text(), nullable=False),
    sa.Column('decision_id', sa.BigInteger(), nullable=True),
    sa.Column('changed_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['decision_id'], ['ai_decisions.id'], name=op.f('fk_config_parameter_history_decision_id_ai_decisions')),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_config_parameter_history'))
    )
    op.create_table('performance_daily_revisions',
    sa.Column('id', sa.BigInteger(), autoincrement=True, nullable=False),
    sa.Column('performance_daily_id', sa.BigInteger(), nullable=False),
    sa.Column('previous_values', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('new_values', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('reason', sa.Text(), nullable=False),
    sa.Column('revised_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['performance_daily_id'], ['performance_daily.id'], name=op.f('fk_performance_daily_revisions_performance_daily_id_performance_daily')),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_performance_daily_revisions'))
    )
    op.create_table('product_current_state',
    sa.Column('product_id', sa.BigInteger(), nullable=False),
    sa.Column('state', sa.Enum('DISCOVERY', 'QUALIFICATION', 'CANDIDATE', 'TEST', 'ACTIVE', 'WINNER', 'REJECTED', 'PAUSED', 'UNDER_REVIEW', 'REPLACED', 'EXPIRED', name='product_state'), nullable=False),
    sa.Column('since', sa.DateTime(timezone=True), nullable=False),
    sa.Column('last_transition', sa.BigInteger(), nullable=True),
    sa.ForeignKeyConstraint(['last_transition'], ['product_state_transitions.id'], name=op.f('fk_product_current_state_last_transition_product_state_transitions')),
    sa.ForeignKeyConstraint(['product_id'], ['products.id'], name=op.f('fk_product_current_state_product_id_products')),
    sa.PrimaryKeyConstraint('product_id', name=op.f('pk_product_current_state'))
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('product_current_state')
    op.drop_table('performance_daily_revisions')
    op.drop_table('config_parameter_history')
    op.drop_index('ix_budget_ledger_ledger_date_scope', table_name='budget_ledger')
    op.drop_table('budget_ledger')
    op.drop_table('ads')
    op.drop_index('ix_product_state_transitions_product_id_created_at', table_name='product_state_transitions')
    op.drop_table('product_state_transitions')
    op.drop_index('ix_product_snapshots_product_id_captured_at', table_name='product_snapshots')
    op.drop_table('product_snapshots')
    op.drop_index('uq_portfolio_products_active_product', table_name='portfolio_products', postgresql_where=sa.text('exited_at IS NULL'))
    op.drop_table('portfolio_products')
    op.drop_table('performance_scores')
    op.drop_index('ix_performance_daily_product_id_metric_date', table_name='performance_daily')
    op.drop_table('performance_daily')
    op.drop_index('ix_opportunity_scores_product_id_computed_at', table_name='opportunity_scores')
    op.drop_table('opportunity_scores')
    op.drop_table('creatives')
    op.drop_index('ix_ai_decisions_created_at', table_name='ai_decisions')
    op.drop_table('ai_decisions')
    op.drop_index('ix_affiliate_links_product_id_active', table_name='affiliate_links', postgresql_where=sa.text('revoked_at IS NULL'))
    op.drop_table('affiliate_links')
    op.drop_table('products')
    op.drop_index('ix_conversions_raw_sub_id_conversion_date', table_name='conversions_raw')
    op.drop_table('conversions_raw')
    op.drop_table('ad_sets')
    op.drop_table('workflow_runs')
    op.drop_table('simulations')
    op.drop_table('portfolio_snapshots')
    op.drop_table('marketplaces')
    op.drop_table('llm_calls')
    op.drop_table('idempotency_keys')
    op.drop_table('execution_locks')
    op.drop_table('config_parameters')
    op.drop_table('campaigns')
    op.drop_table('audit_logs')
    op.drop_table('alerts')
    op.drop_table('ai_recommendations')
    op.drop_table('ad_metrics_raw')
    # ### end Alembic commands ###
